### ISSUE TITLE
MicrometerMetrics should have a "flexypool" prefix and a poolname=uniqueName parameter in the metrics

### ISSUE THREAD

**Issue by atokle** [vladmihalcea/flexy-pool#61] opened 2020-09-11 14:42 UTC

**Comment by vladmihalcea** [comment] 2020-09-11 14:52
Would you like to submit a PR with the fix? I won't have the time to address any issue for this project until 2021 as I'd be very busy until then.

**Comment by atokle** [comment] 2020-09-11 15:36
> Would you like to submit a PR with the fix? I won't have the time to address any issue for this project until 2021 as I'd be very busy until then.

I tried to push a branch with the fix, but got a 403. Do you need to give me access?

**Comment by vladmihalcea** [comment] 2020-09-11 15:46
Did you fork the project first? I think you tried to push to my own fork, instead of yours. The PR can be created from your own fork.

**Comment by atokle** [comment] 2020-09-11 16:24
I did not fork. Did it now, and created a PR #62

**Comment by vladmihalcea** [comment] 2020-09-14 14:13
I think this issue is a duplicate of #60, so I'll close it and leave that one instead

**Closed by vladmihalcea** 2020-09-14 14:13 UTC
